spring:
  profiles:
    active:
    - local

  redis:
    #host: 198.13.47.188
    host: 127.0.0.1
    port: 6379
    
server:
  port: 8443
  ssl:
    enabled: true
    key-store: C:/Program Files/Java/jdk1.8.0_121/bin/test.jks # 1번에서 생성한 Key store 경로와 파일명을 적어줍니다. 
    key-store-password: tjsqhd  # 1번에서 생성한 Key store의 비밀번호를 적어줍니다.
    key-password: tjsqhd # 1번에서 생성한 키스토어의 마지막의 키 비밀번호
    key-alias: test # 키 스토어 별칭
    trust-store: C:/Program Files/Java/jdk1.8.0_121/bin/tsts.ts # 2번에서 생성한 Trust-Store 경로
    trust-store-password: tjsqhd # Trust-Store 비밀번호